Revert "[TouchLatency] Update style of touch latency"
This reverts commit cb03d1f5240d429e6ec5d4ef9fc0091a98f8f8d1.

Reason for revert: Build error with Android Studio:
ERROR: /frameworks/base/tests/TouchLatency/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml:1630: AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

Change-Id: I16091f405475a57156a4d62b7dad0853530ab81d