Adding keep annotation for Plugin Provider Dependencies
Realized that proguard would strip the plugin provider depencencies in
builds due to plugins being loaded dynamically. In user/userdebug
builds with plugins, the MaxBrightnessCap Plugin would face a
NoSuchMethodError for getDisplayDeviceConfigs

Bug: 469871718
Flag: EXEMPT BUGFIX
Test: Built android and verified error was gone.
Change-Id: I55800696bba1ad74da1b0fc6300cdace0502680e